### PR TITLE
[WIP] complete overhaul

### PR DESCRIPTION
**Pull request by bahamas10**
will document later.

### CODE REVIEW

**Comment by ayr-ton** [comment]
WTF does these commits mean?  ¯\_(ツ)_/¯

Confuse travolta

**Comment by bmedicke** [comment]
```git commit -m "$(curl -s whatthecommit.com/index.txt)"```

**Comment by TwizzyDizzy** [comment]
It seems that this PR is now, at least in parts, obsolete, right? (in lights of #14)

**Comment by bahamas10** [comment]
yes.  this PR is largely garbage now. i'm considering making a new command, like `hueadm` or something, that can allow you to manage your hue completely over the CLI, and not just set a light here and there.

I will support both still though, `hue-cli` is here to stay

**Comment by bahamas10** [comment]
For anyone following this project, i have created https://github.com/bahamas10/hueadm.  `hueadm` is a tool meant for actually managing a Hue bridge... it supports a LOT more options than `hue-cli`

**Comment by TwizzyDizzy** [comment]
NIce! Gonna give it a shot in the near future!

Cheers
Thomas

**Pull request closed without merging**
